### ISSUE TITLE
Auto-Generate hmtl files to avoid having them in git

### ISSUE THREAD

**Issue by asantacreu** [juangallostra/BetaLibrary#11]
Auto-Generate hmtl files to avoid having them in git.

Maybe this will be a problem in the server part, needs a little investigation.

**Comment by juangallostra** [comment]
Since Heroku only provides read-only temporary storage we will have to connect the instance to an external storage provider such as amazon S3. I will investigate this option.

**Comment by juangallostra** [comment]
Closing in favor of #45
