### ISSUE TITLE
Add zone links in homepage to the new area maps

### ISSUE THREAD

**Issue by juangallostra** [juangallostra/BetaLibrary#15]
## Zones

- [x]  Can Boquet

- [x] Can Barto

- [x] Can Camps

- [x] Targasonne

- [x] El Cogul

- [x] Albarracín

- [x] Les Puelles

- [x] Switzerland zones

- [x] Bagni di Masino 

- [x] Ailefroide

- [x] Fontainebleau

- [x] Bullenheimer Berg

- [x] Laurenzo boulderfels

- [x] La Pedriza

- [x] Santa Blocona

- [x] La Jonquera

- [x] Canada zones

- [x] Fussimanya

- [x] Montgai

**Comment by juangallostra** [comment]
@asantacreu the area of Cavallers is missing the parking coordinates because when I added it I wasn't able to find any references to the parking locations. Do you know them so that we can add them to the map?

https://github.com/juangallostra/BetaLibrary/blob/b2a10647f1d1a2e5c59857a28666b11af9ebca68/data/cavallers/cavallers.txt#L6-L7

**Comment by juangallostra** [comment]
Related PR: #21 

@asantacreu I think that the only thing missing to close the issue are the parking coordinates of Cavallers.

**Comment by asantacreu** [comment]
Argh, I think changing branches I lost this change..

**Comment by asantacreu** [comment]
@juangallostra Added in master, should work know.
