### ISSUE TITLE
Improve zone detail page

### ISSUE THREAD

**Issue by asantacreu** [juangallostra/BetaLibrary#17]
Some things are not as documented:
- Topo Guide should be a section as it may contain more than one link.
- In this page the map should be smaller, like a minimap. Maybe it could come with a fullscreen button. Consider something like:
![Screenshot_20190819-105410](https://user-images.githubusercontent.com/34898093/63252518-3ef6d400-c270-11e9-957b-8f0dca7e5643.png)

- The playlist section with the playlists embedded is missing

This issue is to focus on the format of the page, the content will be added later in another Issue.
If in need, this Issue could be splitted.

**Comment by asantacreu** [comment]
I fear that if there is an html for every zone, any change that we want to apply at all zones could be a pain. 
Can we explore if we could generate the htmls with some data like how it's done with the map?
I think the information is the same for all the zones so it shouldn't be a lot of trouble.

I think the data could contain:
- Internal link of the zone
- Title of the zone
- List of guides links of the zone
- Map of the zone
- List of Sectors
--For each sector: Name and link to the playlist.

With this information we could have a single htmp that acts as template and fill it with the data to generate each final html.

**Comment by juangallostra** [comment]
@asantacreu I completely agree in that we should avoid having to manually edit all the html files each time we want to make a change.

**Comment by juangallostra** [comment]
@asantacreu The automation of html generation for each zone's page is already done. (Commits: bb53562b8c9d468d5b5c235651b52bf097d56690, c93bf17b6d8516d4a3e8991f041472ef8e4a9fdc, 2438268f1bd5259d5d9699a0ee18ff7dcc11afd4 and ed5c55ebe9d7e57553b4ecc8da5ba29233ebf1fd)

**Comment by juangallostra** [comment]
The new script `generate_pages.py` works in a similar way as `generate_templates.py`. From the datafiles and the template `zone_layout.html` generates the page for each of the zones under the folder `templates/zones`

**Comment by asantacreu** [comment]
Nice work! @juangallostra 
Some thing I see missing:
- The guides should have to option to have a custom name. So a guide should be formed of link + name. 
- Make sure that it is working for more than one guide

**Comment by juangallostra** [comment]
- [ ] The guides should have to option to have a custom name. So a guide should be formed of link + name.
- [ ] Make sure that it is working for more than one guide.

**Comment by juangallostra** [comment]
@asantacreu the first iteration of the zone page looks like:

![Selection_061](https://user-images.githubusercontent.com/9968427/64187696-5e495000-ce71-11e9-9d3c-a05478bac614.png)

To add the sector's playlists I have added two new fields in the datafiles of the sectors that look like:
```
    "playlist":"PLlwn5IhJiUnMVy8ahlvukKmwpekfCBgY2",
    "sectors_playlists":[
        {
            "sector":"Surprise du chef",
            "link":"PLlwn5IhJiUnMzdG7RKO8jhMa87UufZP2K"
        }
    ]
```
Where playlist is the full playlist (it is also used to compute the number of videos of each zone) and `sectors_playlist` is a list of the individual playlists. Each entry should contain the name of the sector and the ID/link of the playlist.

I have already added the full playlists of all the zones, but the individual playlists of each sector have to be added.

**Comment by asantacreu** [comment]
@juangallostra Looks perfect! I'll add the rest of the playlists

**Comment by asantacreu** [comment]
@juangallostra in PC the map appears aligned to the left. It should be centered.

**Comment by juangallostra** [comment]
@asantacreu I've centered both the map and playlists:

![Selection_062](https://user-images.githubusercontent.com/9968427/64354985-b498c900-d000-11e9-840f-1c45e1215a51.png)

**Comment by asantacreu** [comment]
Looks good now!
