### ISSUE TITLE
Show a PopUp when clicking zone's marker

### ISSUE THREAD

**Issue by asantacreu** [juangallostra/BetaLibrary#18]
We should investigate to show something like 27crags do:
![image](https://user-images.githubusercontent.com/34898093/63251418-fc33fc80-c26d-11e9-8e8e-567836b184a1.png)

Maybe we could add information of how many videos we have (this information could be obtained from the full playlist of each zone).

Then, instead of clicking the marker resulting in going to the zone page, it will show this PopUp with a link to be clicked to go to the zone page.

**Comment by juangallostra** [comment]
@asantacreu we can show a popup with custom `html` for each marker (when clicked) shown in the general map. We can define a general template in `html` that defines the content we will show in the popup and, for each area, fill it with specific data.

**Comment by asantacreu** [comment]
@juangallostra Sound good! For the moment we can fill it with the link of the detail zone page.
A nice to have would be the number of videos of videos of that zone, but don't trouble yourself too much, it cna be done for next version.

**Comment by juangallostra** [comment]
@asantacreu something like that?

![Captura](https://user-images.githubusercontent.com/9968427/63493894-e1a39280-c4bc-11e9-8f8b-158447acc503.PNG)

**Comment by asantacreu** [comment]
@juangallostra With the name as the link it should be enough I think.
A link called Map when we are already in the map could be confusing..

**Comment by juangallostra** [comment]
Something like this:

![Captura](https://user-images.githubusercontent.com/9968427/63498705-b9209600-c4c6-11e9-94f8-ef786f0f62b4.PNG)

**Comment by asantacreu** [comment]
Yes, that looks great!
