### ISSUE TITLE
Add number of videos in marker's popup

### ISSUE THREAD

**Issue by asantacreu** [juangallostra/BetaLibrary#23]
Add number of videos in marker's popup.

Below the link we could show: "X videos".

**Comment by juangallostra** [comment]
@asantacreu the API cost of querying the number of videos of all the zones is 3 :sweat_smile: 

I will anyway cache the result for 24 hours.

**Comment by juangallostra** [comment]
Done as per commits 393973947848dbef54119e3369c3a3525e497332 to 2e0c60a0c4d593d9259bdd5086649d599721f5a4.
