### ISSUE TITLE
Move Page Title below Menu

### ISSUE THREAD

**Issue by asantacreu** [juangallostra/BetaLibrary#26]
I thinks its better to show the title below the menu.

It should be formatted specially to be differentiated from the titles of each section. Maybe with a bigger font size and bold it will do.

Maybe adding some kind of separator..

**Comment by juangallostra** [comment]
@asantacreu do you mean to show the name of the zone below the menu?

**Comment by asantacreu** [comment]
@juangallostra Correct. The other pages like 'all', too.

**Comment by juangallostra** [comment]
@asantacreu should I place Madboulder's logo above the Menu then? 

Related issue: #25

**Comment by asantacreu** [comment]
@juangallostra Not above but inside. I'll add an example in issue #25

**Comment by juangallostra** [comment]
Done as per commits: c0c120152ec418dd1a1aa98f87e25e11775fdabb, de7a38b6cfd9f612b68b69602d29b45b8dda5c9a and  99116dba8b1e727de8b7939a54a71f5c6dac1300

**Comment by asantacreu** [comment]
Looks good now, but there is a white space between the menu and the browser's navigation bar in Pc. Can we remove it?

**Comment by juangallostra** [comment]
> Can we remove it?

Done as per commit 36d8f6e15b498cc3fe91483b1a67db693ce57b4e
