### ISSUE TITLE
Unify sectors and sectors_playlists in xml

### ISSUE THREAD

**Issue by asantacreu** [juangallostra/BetaLibrary#27]
Unify sectors and sectors_playlists in xml.

We now have an item called _sectors_ with _name_, _data_ and _link_.
And another item called _sectors_playlists_ with _sector_ and _link_.

The _name_ - _sector_ and the _link_ will always be the same in both items, so I think we should have a single item called _sectors_ with _name_, _data_ and _link_.

**Comment by juangallostra** [comment]
@asantacreu true

**Comment by juangallostra** [comment]
Done as per commit fffb61e607769e1bf92cecfef5a6f4e5731b3a30
