### ISSUE TITLE
Change markers

### ISSUE THREAD

**Issue by juangallostra** [juangallostra/BetaLibrary#3]
Instead of showing the number of sectors for an area show the MadBoulder icon

**Comment by asantacreu** [comment]
If you need the logo modified we could ask Carles but we need to tell him the size we expect.

**Comment by juangallostra** [comment]
@asantacreu I've been checking the different options we have and I think that the best option would be to design or create the whole marker ourselves as an image (both the form we want the marker to have + the logo) and use it the custom image to show a marker. Something like:

![marker-demo](https://user-images.githubusercontent.com/9968427/63335433-9f077c00-c33d-11e9-8073-a10b2352bcf8.png)
 
that would be used instead of the white markers + number we have now.

**Comment by juangallostra** [comment]
The code is already prepared, as per commits 9739cc10daeb9989dbf650354daabd1b9ab72d5a, c1167bdc37002e907c42b8483b04039b525a2591 and cd78cfc34390b0d3b4eeabfbfbe6291421ebd30a to use custom markers. Now we have to design the marker we want to use. 

Meanwhile, I'm using the marker I posted above, which makes the map look like:

![Captura](https://user-images.githubusercontent.com/9968427/63340216-cca4f300-c346-11e9-8d8d-dc392a8e2b07.PNG)

**Comment by asantacreu** [comment]
Can you try using only the logo without the red arrow as 27crags does?
I suppose that the image should be centered in the middle then, not in the bottom.

**Comment by juangallostra** [comment]
@asantacreu for sure! Which version (colors) of the logo?

**Comment by asantacreu** [comment]
@juangallostra Black/White

**Comment by juangallostra** [comment]
@asantacreu Last question, should I also modify it so that the marker is circular instead of square?

**Comment by asantacreu** [comment]
@juangallostra Yes, I think it will be better

**Comment by juangallostra** [comment]
Something like this @asantacreu  ?

![Captura](https://user-images.githubusercontent.com/9968427/63341741-2d81fa80-c34a-11e9-9b90-004c6ec5dd27.PNG)

**Comment by asantacreu** [comment]
That looks awesome!

**Comment by juangallostra** [comment]
As per commit 7963e35952fdae5c22eb1915f745f137f44c80ca
