### ISSUE TITLE
Info PopUp of sectors is not showing accents properly

### ISSUE THREAD

**Issue by asantacreu** [juangallostra/BetaLibrary#31]
Info PopUp of sectors is not showing accents properly.

For example in Targasonne where many sectors have accents like Carrière, Thémis or Créatura.

![image](https://user-images.githubusercontent.com/34898093/65466015-f4afd680-de5d-11e9-96b1-051e2c65cb1f.png)

**Comment by juangallostra** [comment]
@asantacreu nice catch! Fixed as per commit fb0f3fb28c17bae3f5e50b951351e4097a787aef

![Screenshot from 2019-09-24 17-42-36](https://user-images.githubusercontent.com/9968427/65527466-f7104000-def2-11e9-836f-9aee3b36653b.png)
