### ISSUE TITLE
Change parking icon

### ISSUE THREAD

**Issue by asantacreu** [juangallostra/BetaLibrary#38]
The parking icon should be something like a white P in blue background.

**Comment by juangallostra** [comment]
@asantacreu the icon set we are currently using does not have any parking icon. I've tried doing it myself (see image below) but I am not really happy with the result. If you could provide me an image of the desired icon I can use it for signaling parkings.

![p_icon](https://user-images.githubusercontent.com/9968427/66507071-ce7d6e00-eace-11e9-9d0c-31b88e694a2f.png)

**Comment by asantacreu** [comment]
![parking](https://user-images.githubusercontent.com/34898093/66824358-69030480-ef48-11e9-9a0f-93c36f59d569.png)
Maybe this one will work.

**Comment by juangallostra** [comment]
@asantacreu this is an example preview of the zone map (Targasonne) with the new parking icons. If you like it I will update all the maps with the new icon.

![p1](https://user-images.githubusercontent.com/9968427/68548928-88c80400-03f2-11ea-9aba-12f15f3e83ff.png)

**Comment by asantacreu** [comment]
@juangallostra Looks Good to Me!
