### ISSUE TITLE
Add "latest videos" section

### ISSUE THREAD

**Issue by asantacreu** [juangallostra/BetaLibrary#6]
Add "latest videos" section.

This section should have embedded the 5 last videos uploaded in the channel.

I hope YouTbe has an API that gives this information, maybe we should investigate a little bit.

**Comment by juangallostra** [comment]
A query like: `GET https://www.googleapis.com/youtube/v3/search?part=snippet&channelId={CHANNEL_ID}&maxResults=5&order=date&type=video&key={YOUR_API_KEY}` should do the trick.

Reference: https://stackoverflow.com/questions/32074112/youtube-api-3-get-latest-videos

**Comment by juangallostra** [comment]
@asantacreu the section is already available. Currently, it is located at the bottom of the landing page. Should it be located elsewhere?

**Comment by asantacreu** [comment]
> @asantacreu the section is already available. Currently, it is located at the bottom of the landing page. Should it be located elsewhere?

Looks awesome :)

Yeah, I think it'd better be in a new Menu section called Latest Videos placed between "Zones" and "About Us" sections

**Comment by juangallostra** [comment]
Done as per commit 231a904f41344744311bfd395a83a5b68b4a561d
