### ISSUE TITLE
Main Menu should be visible always

### ISSUE THREAD

**Issue by asantacreu** [juangallostra/BetaLibrary#8]
Main Menu should be visible always. At least in PC to ease navigation.
If the Menu in Mobile is vertical and not horizontal we could explore another option such:
- Make the menu horizontal
- Hide/Show the menu with a button
..

**Comment by juangallostra** [comment]
> Main Menu should be visible always. At least in PC to ease navigation

Commit 6972fda55ecb2107e2abc5fd54b80e53dfe0571e solves that.

**Comment by juangallostra** [comment]
> Hide/Show the menu with a button

Commit 117cb0bd929f619940d17d226728d03a4a8cc9fc solves that.

**Comment by asantacreu** [comment]
With this change the sections lost its boldness.
Also, in Pc, they were splitted equally among the space available, not aligned to the left.
