### ISSUE TITLE
Optimize number of youtube API queries

### ISSUE THREAD

**Issue by juangallostra** [juangallostra/BetaLibrary#9]
Each time someone clicks the _latest videos_ tab, the page performs a query to the YouTube API to retrieve the last 6 videos. The free API tier only allows us to 10000 queries a day and, from my experience, we are reaching that number of queries each day. (I am not sureif retrieving the 6 most recent videos counts as 1 or 6 queries.)

Maybe we can cache the result of the first query of the day and only query again if a certain amount of time since the last call has passed. That, or maybe upgrade the plan we are using.

What are your thoughts on this @asantacreu ?

**Comment by asantacreu** [comment]
@juangallostra I think that cacheing the results would do the trick. If this is done when a minute has passed, worst case scenario would be 8640 queries a day.

**Comment by juangallostra** [comment]
Done as per commit 728b8c12827d430bea7d21ef3f75f7ecb9cc04ca

Note that this change adds a new required package, `Flask-Caching`.

**Comment by asantacreu** [comment]
Keep in mind to add this new requirement in the Project's ReadMe

**Comment by juangallostra** [comment]
I haven't identified why, but each time each time we obtain the last 6 videos results in 102 queries made to the Youtube API (Google Developer portal has a dashboard that allows to measure this number).  It is weird because we are using this single `GET` to retrieve them:

https://github.com/juangallostra/BetaLibrary/blob/86cdc3a1c5a271cc3f84e4d8fe4ea7e18ce83742/helpers.py#L80

Anyway, this limits the number of queries a day to 98, which means that we are only allowed to update the latest videos section every 15 minutes if we don't want to run out of queries. I don't think it is that bad, so until further diagnosis I have changed the cache timeout to 15 minutes as per commit 75c4c8a3b9bf693df1902ae72768d4b25e6a4fcd

**Comment by asantacreu** [comment]
The cost of a search query is 100, not 1. It can be calculated here: https://developers.google.com/youtube/v3/determine_quota_cost

This would explain the problem.

The cache of 15 minutes would do for now but we should keep an eye on this if we do more queries.
